name: endlessh
networks:
  service:
    name: ${DOCKER_NETWORK:-services}
    external: true
services:
  endlessh:
    image: shizunge/endlessh-go
    container_name: endlessh
    restart: unless-stopped
    profiles: [service]
    networks:
      - service
    ports:
      - 22:2222
      # - 2112:2112
    environment:
      TZ: ${TZ:-America/Caracas}
    command:
      - -interval_ms=1000
      - -logtostderr
      - -v=1
      - -enable_prometheus
      - -geoip_supplier=ip-api
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - glance.name=Endlessh
      - glance.icon=mdi:ssh
      - glance.description=Endlessh is a SSH honeypot that listens on port 22 and responds with a fake SSH server.
