name: excalidraw
networks:
  default:
    name: ${DOCKER_NETWORK:-proxy}
    external: true
services:
  excalidraw:
    build:
      context: ./excalidraw
    container_name: excalidraw
    # ports:
    #   - 80:80
    restart: unless-stopped
    stdin_open: true
    mem_limit: 10mb
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - glance.icon=di:excalidraw
      - glance.url=${GLANCE_URL}
      - glance.name=Excalidraw
      - glance.description=Excalidraw is a whiteboard tool that lets you easily sketch diagrams that have a hand-drawn feel to them.
