name: hoppscotch
networks:
  default:
    name: ${DOCKER_NETWORK:-proxy}
    external: true
  database:
    name: ${DATABASE_NETWORK:-databases}
    external: true
services:
  hoppscotch:
    image: hoppscotch/hoppscotch
    container_name: hoppscotch
    restart: unless-stopped
    networks:
      - default
      - database
    env_file:
      - .env
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - glance.icon=di:hoppscotch
      - glance.url=${GLANCE_URL}
      - glance.name=Hoppscotch
      - glance.description=Hoppscotch is an open-source API development ecosystem.
