name: ${STACK_NAME:-postgres}
networks:
  database:
    name: ${DATABASE_NETWORK:-database}
    external: true
services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres
    restart: unless-stopped
    profiles:
      - ${SERVICE_PROFILE:-database}
    stop_signal: SIGINT
    networks:
      - database
    ports:
      - ${PORTS:-5432}:5432
    environment:
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASS}
      POSTGRES_DB: ${DB_NAME}
      TZ: ${TZ:-America/Caracas}
      POSTGRES_INITDB_ARGS: --data-checksums
    volumes:
      - ${DATA_DIR:-./data}:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${USER}", "-d", "${DB_NAME}"]
      start_period: 1m
      start_interval: 10s
      interval: 1m
      timeout: 5s
      retries: 3
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - glance.icon=di:postgres
      - glance.name=Postgres
      - glance.description=PostgreSQL is a powerful, open source object-relational database system.
