name: ${STACK_NAME:-excalidraw}
networks:
  proxy:
    name: ${TOOL_NETWORK:-proxy}
    external: true
services:
  excalidraw:
    image: excalidraw/excalidraw
    container_name: excalidraw
    restart: unless-stopped
    profiles:
      - ${SERVICE_PROFILE:-tool}
    networks:
      - proxy
    # ports:
    #   - 80:80
    stdin_open: true
    mem_limit: 10mb
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - glance.icon=di:excalidraw
      - glance.url=${GLANCE_URL}
      - glance.name=Excalidraw
      - glance.description=Excalidraw is a whiteboard tool that lets you easily sketch diagrams that have a hand-drawn feel to them.
