name: ${STACK_NAME:-docuseal}
networks:
  proxy:
    name: ${TOOL_NETWORK:-proxy}
    external: true
  database:
    name: ${DATABASE_NETWORK:-database}
    external: true
services:
  docuseal:
    image: docuseal/docuseal:latest
    container_name: docuseal
    restart: unless-stopped
    profiles:
      - ${SERVICE_PROFILE:-tool}
    networks:
      - proxy
      - database
    # ports:
    #   - 3000:3000
    volumes:
      - ${DATA_DIR:-./data}:/data/docuseal
    environment:
      # User your host domain for FORCE_SSL
      # FORCE_SSL: ${FORCE_SSL:-ds.localhost}
      # Remember to encode your postgres password https://www.urlencoder.org/
      DATABASE_URL: ${DATABASE_URL:-postgresql://user:password@postgres:5432/docuseal}
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - glance.icon=di:docuseal
      - glance.url=${GLANCE_URL}
      - glance.name=Docuseal
      - glance.description=Docuseal is a open-source tool to streamline document filling and signing.
