name: ${STACK_NAME:-npm}
networks:
  proxy:
    name: ${SERVICE_NETWORK:-service}
    external: true
  database:
    name: ${DATABASE_NETWORK:-database}
    external: true
services:
  npm:
    image: docker.io/jc21/nginx-proxy-manager:latest
    container_name: npm
    restart: unless-stopped
    profiles:
      - ${SERVICE_PROFILE:-service}
    networks:
      - proxy
      - database
    ports:
      - 80:80
      - 443:443
      # - 81:81
    environment:
      DB_MYSQL_HOST: ${DB_HOST}
      DB_MYSQL_PORT: ${DB_PORT}
      DB_MYSQL_USER: ${DB_USER}
      DB_MYSQL_PASSWORD: ${DB_PASS}
      DB_MYSQL_NAME: ${DB}
      TZ: ${TZ:-America/Caracas}
      TP_THEME: dark
    healthcheck:
      test: ["CMD", "/usr/bin/check-health"]
      interval: 10s
      timeout: 3s
    volumes:
      - ${DATA_DIR:-./data}:/data
      - ${CERTS_DIR:-./certs}:/etc/letsencrypt
      - ./theme:/etc/cont-init.d/99-themepark
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - glance.icon=di:nginx-proxy-manager
      - glance.url=${GLANCE_URL}
      - glance.name=Nginx Proxy Manager
      - glance.description=Reverse proxy manager for nginx. It provides a web interface to manage your reverse proxy settings, SSL certificates, and more.
