name: ${STACK_NAME:-newt}
networks:
  proxy:
    name: ${SERVICE_NETWORK:-service}
    external: true
services:
  newt:
    image: fosrl/newt
    container_name: newt
    restart: unless-stopped
    profiles:
      - ${SERVICE_PROFILE:-service}
    networks:
      - proxy
    environment:
      PANGOLIN_ENDPOINT: ${ENDPOINT}
      NEWT_ID: ${ID}
      NEWT_SECRET: ${SECRET}
      TZ: ${TZ:-America/Caracas}
      DOCKER_SOCKET: /var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - glance.icon=di:pangolin
      - glance.name=Newt
      - glance.description=Tunneling client for Pangolin
