name: ${STACK_NAME:-jackett}
networks:
  proxy:
    name: ${PROXY_NETWORK:-proxy}
    external: true
services:
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    restart: unless-stopped
    profiles:
      - ${SERVICE_PROFILE:-servarr}
    networks:
      - proxy
    # ports:
    #   - 9117:9117
    environment:
      PUID: 1000
      PGID: 1000
      TZ: ${TZ:-America/Caracas}
      DOCKER_MODS: ghcr.io/themepark-dev/theme.park:jackett
      TP_THEME: dark
    volumes:
      - ${CFG_DIR:-./cfg}:/config
      - ${DOWN_DIR:-./downloads}:/downloads
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - glance.icon=di:jackett
      - glance.url=${GLANCE_URL}
      - glance.name=Jackett
      - glance.description=Jackett is a single place for your torrent needs.
