name: ${STACK_NAME:-qbittorrent}
networks:
  proxy:
    name: ${PROXY_NETWORK:-proxy}
    external: true
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    restart: unless-stopped
    profiles:
      - ${SERVICE_PROFILE:-servarr}
    networks:
      - proxy
    ports:
      - 6881:6881/udp
      - 6881:6881
      # - 8080:8080
    environment:
      PUID: 1000
      PGID: 1000
      TZ: ${TZ:-America/Caracas}
      WEBUI_PORT: 8080
      DOCKER_MODS: ghcr.io/vuetorrent/vuetorrent-lsio-mod:latest
    volumes:
      - ${CFG_DIR:-./cfg}:/config
      - ${DOWN_DIR:-./downloads}:/downloads
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - glance.icon=di:vuetorrent
      - glance.url=${GLANCE_URL}
      - glance.name=VueTorrent
      - glance.description=Qbittorrent is a free and open-source BitTorrent client.
