name: ${STACK_NAME:-bytebase}
networks:
  proxy:
    name: ${TOOL_NETWORK:-proxy}
    external: true
  database:
    name: ${DATABASE_NETWORK:-database}
    external: true
services:
  bytebase:
    container_name: bytebase
    image: bytebase/bytebase:${VERSION:-3.8.0}
    restart: unless-stopped
    profiles:
      - ${SERVICE_PROFILE:-tool}
    networks:
      - proxy
      - database
    # ports:
    #   - 8080:8080
    volumes:
      - ${DATA_DIR:-./data}:/var/opt/bytebase
    command: --data /var/opt/bytebase --pg ${PG_URL:-postgresql://user:password@postgres:5432/bytebase} --external-url ${EXTERNAL_URL:-https://bytebase.domain.com} --disable-sample --disable-metric
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - glance.icon=https://www.bytebase.com/favicon/favicon.png
      - glance.url=${GLANCE_URL}
      - glance.name=Bytebase
      - glance.description=Bytebase is a open-source tool to streamline document filling and signing.
