name: glance
networks:
  proxy:
    name: ${DOCKER_NETWORK:-proxy}
    external: true
services:
  glance:
    container_name: glance
    image: glanceapp/glance
    restart: unless-stopped
    profiles: [app]
    networks:
      - proxy
    # ports:
    #   - 8080:8080
    env_file: .env
    volumes:
      - ./cfg:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
    healthcheck:
      test: [CMD, wget, --spider, -q, http://localhost:8080/api/healthz]
      interval: 60s
      timeout: 10s
      start_period: 60s
      retries: 5
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - glance.icon=di:glance
      - glance.url=${GLANCE_URL}
      - glance.name=Glance
      - glance.description=See everything at a glance
