name: ${STACK_NAME:-openwebui}
networks:
  proxy:
    name: ${PROXY_NETWORK:-proxy}
    external: true
services:
  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: openwebui
    restart: unless-stopped
    profiles:
      - ${SERVICE_PROFILE:-app}
    networks:
      - proxy
    # ports:
    #   - 8080:8080
    environment:
      TZ: ${TZ:-America/Caracas}
      ENABLE_RAG_WEB_SEARCH: True
      RAG_WEB_SEARCH_ENGINE: searxng
      RAG_WEB_SEARCH_RESULT_COUNT: 3
      RAG_WEB_SEARCH_CONCURRENT_REQUESTS: 10
      SEARXNG_QUERY_URL: http://searxng:8080/search?q=<query>
    volumes:
      - ${DATA_DIR:-./data}:/app/backend/data
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - glance.icon=di:openwebui
      - glance.url=${GLANCE_URL}
      - glance.name=OpenWebUI
      - glance.description=OpenWebUI is a web client for LLMs.
