name: mariadb
networks:
  default:
    name: ${DOCKER_NETWORK:-databases}
    external: true
services:
  mariadb:
    image: mariadb
    container_name: mariadb
    restart: unless-stopped
    ports:
      - ${PORT:-3306}:3306
    environment:
      MARIADB_ROOT_PASSWORD: ${ROOT_PASS}
      MARIADB_USER: ${USER}
      MARIADB_PASSWORD: ${PASS}
      TZ: ${TZ:-America/Caracas}
    volumes:
      - ${DATA_DIR:-./data}:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 1m
      start_interval: 10s
      interval: 1m
      timeout: 5s
      retries: 3
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - glance.icon=di:mariadb
      - glance.name=MariaDB
      - glance.description=MariaDB Server is a general purpose open source relational database management system.
