name: ${STACK_NAME:-garage}
networks:
  database:
    name: ${DATABASE_NETWORK:-database}
    external: true
services:
  garage:
    image: dxflrs/garage:v2.0.0
    container_name: garage
    restart: unless-stopped
    profiles:
      - ${SERVICE_PROFILE:-database}
    networks:
      - database
    ports:
      - 3900:3900   ## s3 api
      - 3901:3901   ## rpc
      # - 3902:3902   ## s3 web
      # - 3903:3903   ## admin api and '/metrics' for prometheus
    environment:
      TZ: ${TZ:-America/Caracas}
    volumes:
      - ./garage.toml:/etc/garage.toml
      - ${META_DIR:-./meta}:/var/lib/garage/meta
      - ${DATA_DIR:-./data}:/var/lib/garage/data
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - glance.icon=di:garage
      - glance.name=garage
      - glance.description=garage is a high-performance, S3 compatible object storage system
